### ISSUE TITLE
Getting it to run, missing LibMediaEncoder.so

### ISSUE THREAD

**Issue by burf2000** [Teaonly/android-eye#27]
I have tried opening this in Eclipse and Android Studio, I have installed the NDK for both but I get this error

02-18 20:30:36.288: E/AndroidRuntime(1918): FATAL EXCEPTION: main
02-18 20:30:36.288: E/AndroidRuntime(1918): Process: teaonly.droideye, PID: 1918
02-18 20:30:36.288: E/AndroidRuntime(1918): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/teaonly.droideye-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libMediaEncoder.so"
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at java.lang.System.loadLibrary(System.java:989)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at teaonly.droideye.MainActivity.<clinit>(MainActivity.java:535)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at java.lang.reflect.Constructor.newInstance(Native Method)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at java.lang.Class.newInstance(Class.java:1572)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1065)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at android.os.Looper.loop(Looper.java:135)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at java.lang.reflect.Method.invoke(Native Method)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at java.lang.reflect.Method.invoke(Method.java:372)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
02-18 20:30:36.288: E/AndroidRuntime(1918): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by devm2024** [comment]
Hi Burf.,
             Have you got these working? If yes please let me know how. 
Thanks.

**Comment by AdamFM** [comment]
where i can get libMediaencoder.so?

**Comment by andruwik777** [comment]
The same issue ((

**Comment by shaunsphere** [comment]
same issue , even download a libMediaEncoder.so from https://github.com/drewx2/android_vendor_htc_dlx/tree/master/proprietary/lib

**Comment by MostafaS** [comment]
same issue

**Comment by mbpz** [comment]
How to solve this problem?
dlopen("/data/app-lib/teaonly.droideye-2/libMediaEncoder.so") failed: dlopen failed: cannot locate symbol "_ZN7android8OMXCodec18findMatchingCodecsEPKcbS2_jPNS_6VectorINS_7String8EEEPNS3_IjEE" referenced by "libMediaEncoder.so"...

**Comment by medynets** [comment]
On the github is two different versions of libMediaEncoder.so. The first is for armeabi, the second - for armeabi-v7a. When you use the first vesrsion, Application.mk must declare APP_ABI:= armeabi. When you use the second version, Application.mk must declare APP_ABI:= armeabi-v7a. The first version is of 960 kB length. The second version is of 962 kB length. When confusing versions the compiler gives an error.

**Comment by junaid-umar** [comment]
@medynets can you share links to libMediaEncoder.so?
